{% set data= load_setup_py_data() %}
package:
  name: dm-csc-base
  version: 1.0.0.rc5

source:
  git_url: https://github.com/lsst-dm/dm_csc_base
  git_rev: master

build:
  script: python -m pip install --ignore-installed --no-deps .
  skip: True #[win]

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
